main: Add support for debug local image in docker-compose
In some cases we want to test local builds on the emulator
infrastructure that this app provides. This commit adds support for
debugging local images in the docker-compose file. It adds a new
service called `emulator-debug` that runs the emulator in debug mode
and allows the user to pass a local image path as an argument.
This is done by checking if the `PHOBOS_LOCAL_IMG_PATH` environment
variable is set. If it is set, the `emulator-debug` service will be
used instead of the `emulator` service.

Signed-off-by: Matheus Castello <matheus@castello.eng.br>

diff --git a/phobos-emulator-manager b/phobos-emulator-manager
--- a/phobos-emulator-manager
+++ b/phobos-emulator-manager
@@ -27,6 +27,19 @@ fi
 # make the xhost accessible to the container
 xhost + >/dev/null 2>&1 || true
 
+# check if we are passing an argument
+# if so, the argument need to be a valid file path
+if [ $# -eq 1 ]; then
+    # Check if the provided path is a file and is absolute
+    if [ ! -f "$1" ] || [[ "$1" != /* ]]; then
+        echo "❌ Invalid file path: $1"
+        echo "Please provide a valid absolute file path."
+        exit 69
+    fi
+
+    export PHOBOS_LOCAL_IMG_PATH="$1"
+fi
+
 if [ -z "$WSL_DISTRO_NAME" ]; then
 
     if [ -z "$NO_KVM" ]; then
