torizon-emulator-manager: check for KVM module
Stop the script execution if the KVM module is not found in the system.
Related to #1

Signed-off-by: Matheus Castello <matheus.castello@toradex.com>

diff --git a/torizon-emulator-manager b/torizon-emulator-manager
--- a/torizon-emulator-manager
+++ b/torizon-emulator-manager
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-if ! command -v docker &> /dev/null; then
+if [ ! -e /dev/kvm ]; then
+    echo "❌ KVM module not found. Please make sure it is enabled in your kernel."
+    exit 1
+fi
+
+if [ ! command -v docker &> /dev/null ]; then
     echo "❌ Docker is not installed."
     echo "Please install Docker before running this script."
     exit 1
